### ISSUE TITLE
Index transcribed content

### ISSUE THREAD

**Issue by wolruf** [nragusa/reinventvideos#3]
As an end user, I'd like to find specific terms, words from recorded videos. Obviously, this means some work to transcribe the audio, index it and make it searchable. I don't know if Youtube subtitles are accessible and searchable. Else, Media2Cloud may be used: https://aws.amazon.com/ec2/pricing/on-demand/

This should be optional in search results to avoid being overwhelmed with results when searching for "EC2".

**Comment by nragusa** [comment]
I've definitely thought of this too, but decided not to implement because the value didn't quite seem there. I used Amazon Transcribe to translate the podcast version of re:Invent sessions, but the translation came out subpar - mostly because much of the speech is in acronyms or otherwise odd words. I haven't experimented with using a custom vocabulary, which might help to improve the translation.
